name: Publish to GitHub Pages

on:
  push:
    branches: ["main"]

env:
  NODE_AUTH_TOKEN: ${{ secrets.PAGES_DEPLOYMENT }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v1